bitbag_ing_initialize_payment:
  path: /payment/ing/initialize_payment
  methods: [PUT]
  controller: bitbag.sylius_ing_plugin.controller.shop.initialize_payment_controller

bitbag_ing_redirect:
  path: /payment/ing/redirect/{status}/{paymentId}
  methods: [GET]
  controller: bitbag.sylius_ing_plugin.controller.shop.redirect_controller


bitbag_ing_one_click_redirect:
  path: /payment/ing/oneclick/redirect/{status}/{paymentId}
  controller: bitbag.sylius_ing_plugin.controller.shop.oneclick.redirect_one_click_controller
