sylius_resource:
  resources:
    bitbag_sylius_ing_pay_plugin.ing_pay_transaction:
      classes:
        model: BitBag\SyliusIngPayPlugin\Entity\IngPayTransaction
        repository: BitBag\SyliusIngPayPlugin\Repository\IngPayTransaction\IngPayTransactionRepository
        interface: BitBag\SyliusIngPayPlugin\Entity\IngPayTransactionInterface
